In [3]:
import math

In [4]:
print(math.sqrt(2))
print(math.pi)
print(math.sin(math.pi/2))
print(math.cos(math.pi/2))
print(math.log(32, 2))

1.4142135623730951
3.141592653589793
1.0
6.123233995736766e-17
5.0


In [5]:
import numpy as np

In [11]:
print(np.array([-1, 0, 1], dtype=np.int32))
print(np.array([-1, 0, 1], dtype=np.float64))
print(np.array([-1, 0, 1], dtype=np.complex128))
print(np.array([-1, 0, 1], dtype=np.bool_))

[-1  0  1]
[-1.  0.  1.]
[-1.+0.j  0.+0.j  1.+0.j]
[ True False  True]


In [13]:
print(np.array([[1, 2], [3, 4]]))

[[1 2]
 [3 4]]


In [16]:
a1 = np.array([0, 1, 2, 3, 4, 5])
a2 = a1.reshape((3, 2))
print(a2)
print(a2.ravel())

[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


In [17]:
print(np.arange(3))
print(np.arange(0, 1, 0.2))

[0 1 2]
[0.  0.2 0.4 0.6 0.8]


In [18]:
print(np.linspace(0, 1, 4))

[0.         0.33333333 0.66666667 1.        ]


In [22]:
print(np.random.rand(4))
print(np.random.rand(2, 3))

[0.43016604 0.13677166 0.10727838 0.03423815]
[[0.51002772 0.64211874 0.78544433]
 [0.89181589 0.04539954 0.07084839]]


In [29]:
def arange_square_matrix(n):
    return np.arange(n).reshape((n, 1)) + np.arange(n)


In [30]:
print(all(map(all,(arange_square_matrix(3) == np.array([[0,1,2],[1,2,3],[2,3,4]])))))

True


In [34]:
print(np.arange(3).reshape((3, 1)) + np.arange(3))

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [41]:
a = np.arange(5)
print(a)
print(a[1:4])
print(a[:4])
print(a[1:])
print(a[:])
print(a[:-1])
print(a[::2])
print(a[::-2])
print(a[0:5:2])

[0 1 2 3 4]
[1 2 3]
[0 1 2 3]
[1 2 3 4]
[0 1 2 3 4]
[0 1 2 3]
[0 2 4]
[4 2 0]
[0 2 4]


In [43]:
a = np.arange(9).reshape((3, 3))
print(a)
print(a[:2, :2])
print(a[1:, 1:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1]
 [3 4]]
[[4 5]
 [7 8]]


In [45]:
for idx, e in np.ndenumerate(np.arange(6).reshape((2, 3))):
    print(idx, e)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5


In [53]:
a = np.arange(4)
print(a)

print(a + 1)

b = a + 1
print(a/b)
print(1//b)
print(9//b)

[0 1 2 3]
[1 2 3 4]
[0.         0.5        0.66666667 0.75      ]
[1 0 0 0]
[9 4 3 2]


In [57]:
a = np.zeros(3) + 2
print(a)
print(np.sqrt(a))
b = np.zeros((2, 2)) + 2
print(np.sqrt(b))
print(np.sqrt(2))
print(np.sqrt(3))

[2. 2. 2.]
[1.41421356 1.41421356 1.41421356]
[[1.41421356 1.41421356]
 [1.41421356 1.41421356]]
1.4142135623730951
1.7320508075688772


In [59]:
a = np.array([3, 4, -1, 0, 2])
print(a)
print(np.sort(a))

[ 3  4 -1  0  2]
[-1  0  2  3  4]


In [62]:
a = np.arange(6).reshape(2, 3)
print(a)
print(a.sum())
print(a.sum(0))
print(a.sum(1))

[[0 1 2]
 [3 4 5]]
15
[3 5 7]
[ 3 12]


In [64]:
np.savetxt("arange2x3.txt", np.arange(6).reshape(2, 3))

In [67]:
a = np.loadtxt("arange2x3.txt")
print(a)

[[0. 1. 2.]
 [3. 4. 5.]]


In [69]:
a = np.array([0, 1, 2, -3, -4, -5, -6, -7])
print(a)
print(a[a < 0])
print(a[(a < 0) & (a % 2 == 0)])
a[a < 0] = 8
print(a)

[ 0  1  2 -3 -4 -5 -6 -7]
[-3 -4 -5 -6 -7]
[-4 -6]
[0 1 2 8 8 8 8 8]


In [70]:
np.linalg.norm(np.ones(3))

1.7320508075688772