In [3]:
import numpy as np
import torch
 
#入れ子のlistを渡して作成
t = torch.tensor([[1, 2], [3, 4.]])

#0~9までの数値で初期化された1次元のTensor
a = torch.arange(0, 10)

#正規分布で100×10のTensorを作成
c = torch.randn(100, 10)

print(c.size())
print(c)

print(a.size())
print(a)

print(t.size())
print(t)

torch.Size([100, 10])
tensor([[-1.0878e+00,  7.0444e-01, -6.0008e-01,  1.1070e-01, -7.7253e-01,
         -3.7096e-01,  2.4495e+00, -1.8843e+00, -1.0737e+00, -1.0582e+00],
        [-1.0485e+00, -2.2344e-02,  9.4896e-01, -7.8373e-01, -3.9311e-01,
         -1.1316e+00,  1.1876e+00,  1.3564e-01, -1.6682e-01,  1.3657e+00],
        [-6.0454e-01, -5.4363e-01,  1.0914e-01, -4.3926e-01,  1.6065e+00,
         -1.3698e+00,  3.2848e-01, -7.1950e-01, -1.8351e+00,  2.2943e-01],
        [ 1.3145e+00,  4.3375e-01,  4.0971e-01,  7.2720e-01, -4.0243e-01,
          1.3674e+00, -3.4339e-01, -2.3137e-01, -6.9170e-01,  2.5546e+00],
        [ 4.3257e-01,  4.4276e-01,  1.0814e+00,  1.3757e+00, -4.7872e-01,
          2.3119e-02,  5.0972e-01, -1.6503e+00, -8.9145e-01, -6.2971e-01],
        [-8.1771e-01,  7.1162e-01, -9.2730e-01, -1.7843e+00, -5.4373e-01,
         -3.9112e-01,  4.6209e-01,  1.6475e+00,  8.3330e-01, -2.8517e-01],
        [ 4.3604e-01, -1.0365e-01, -2.8551e-02,  5.6579e-03, -3.7079e-02,
          

In [4]:
#numpyメソッドを使用して，ndarrayに変換
a = torch.tensor([[1, 2], [3, 4]])
x = a.numpy()

print(a)
print(x)

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


In [5]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])

#スカラーの添字で指定
print(t[0, 2])

#スライスで指定
print(t[:, :2])

#添字のリストで指定
print(t[:, [1,2]])

#マスク配列を使用して，3より大きい部分のみを選択
print([t>3])

#[0, 1]要素を100にする
t[0,1] = 100

print(t)

#スライスを使用した一括代入
t[:, 1] = 200

print(t)

#マスク配列を使用して，特定条件の要素のみ置換
t[t > 10] = 20
print(t)

tensor(3)
tensor([[1, 2],
        [4, 5]])
tensor([[2, 3],
        [5, 6]])
[tensor([[False, False, False],
        [ True,  True,  True]])]
tensor([[  1, 100,   3],
        [  4,   5,   6]])
tensor([[  1, 200,   3],
        [  4, 200,   6]])
tensor([[ 1, 20,  3],
        [ 4, 20,  6]])


In [6]:
#100×10のテストデータを用意
X = torch.randn(100, 10)

y = X * 2 + torch.abs(X)
print(y)

#平均値を求める
m = torch.mean(X)

#関数ではなく，メソッドとしても利用できる
m = X.mean()

print(m)

#集計結果を0次元のTensorでitemメソッドを使用して，
#値を取り出すことができる
m_value = m.item()
print(m_value)

#集計して列ごとに平均値を計算している
m2 = X.mean(0)
print(m2)

tensor([[ 9.0919e+00,  2.4180e-01, -8.3893e-01, -7.8492e-01, -8.1639e-01,
         -8.4195e-01, -5.0876e-01, -1.1243e+00,  4.2999e+00,  1.7498e+00],
        [-8.9881e-02,  1.6009e+00, -2.9856e-01, -1.8177e+00, -2.8553e+00,
          5.1190e+00, -2.8281e-01,  3.7151e+00,  3.3303e+00, -3.2245e-02],
        [-6.5843e-01, -9.9762e-02,  2.1047e+00,  2.1180e+00, -4.8199e-01,
          4.0371e+00, -1.2527e-03, -8.3340e-01,  8.1717e+00,  1.5279e+00],
        [ 2.0669e-01,  3.8725e+00, -7.3000e-01, -5.0489e-01, -1.3796e+00,
         -4.6989e-01, -1.0833e+00,  2.5783e-01,  2.7785e+00,  2.3774e-01],
        [ 7.8850e-01,  5.6260e+00,  3.4116e+00, -1.3794e+00, -1.7779e+00,
         -1.2235e+00, -2.5472e-01,  2.6735e+00, -3.0657e-01, -1.5443e-01],
        [-1.8479e-01,  2.5224e-01, -2.8041e-01,  1.3916e+00,  1.8859e-01,
          6.1993e-02,  4.1842e+00,  1.2611e+00, -1.5065e-01, -1.9263e+00],
        [-1.9658e+00, -9.1260e-01,  1.3003e+00,  6.2153e+00, -1.0753e+00,
         -1.6983e+00,  1.3189e+0

In [22]:
x1 = torch.tensor([[1, 2], [3, 4.]])
x2 = torch.tensor([[10, 20, 30], [40, 50, 60.]])

print(x2.size())

print(x1.view(4, 1))
print(x1)

print(x1.reshape(4, 1))
print(x1)

print(x2)
#2×3を転置して3×2にする
print(x2.t())
print(x2)

#dim=1に対して結合することで2×5のTensorを作る
torch.cat([x1, x2], dim=1)

#64×32×3のデータが100個
hwc_img_data = torch.rand(100, 64, 32, 3)
print(hwc_img_data)
print(hwc_img_data.size())
#64と32を入れ替えたのちに，32と3を入れ替える
chw_img_data = hwc_img_data.transpose(1, 2).transpose(1, 3)
print(chw_img_data)
print(chw_img_data.size())

torch.Size([2, 3])
tensor([[1.],
        [2.],
        [3.],
        [4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.],
        [3.],
        [4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[10., 20., 30.],
        [40., 50., 60.]])
tensor([[10., 40.],
        [20., 50.],
        [30., 60.]])
tensor([[10., 20., 30.],
        [40., 50., 60.]])
tensor([[[[4.6422e-01, 7.0830e-01, 2.4279e-01],
          [7.9701e-01, 7.9648e-01, 4.6482e-01],
          [3.5251e-03, 1.4177e-01, 5.3509e-01],
          ...,
          [5.5556e-01, 8.1843e-01, 9.7120e-01],
          [7.4992e-01, 5.4843e-01, 2.3781e-01],
          [4.6589e-01, 3.8205e-02, 7.9586e-01]],

         [[8.0160e-01, 3.6827e-01, 4.0895e-01],
          [7.9897e-01, 8.5131e-01, 6.3038e-01],
          [6.4250e-01, 4.2332e-01, 4.1155e-02],
          ...,
          [1.9584e-01, 3.0369e-01, 2.3211e-01],
          [9.5651e-01, 3.2186e-01, 3.5943e-01],
          [5.6546e-01, 7.8789e-03, 5.6136e-01]],

         [[3.9385e-0

In [30]:
m = torch.randn(100, 10)
v = torch.randn(10)

#内積
d = torch.dot(v, v)
print(d)

#100×10の行列と長さ10のベクトルの積
#結果は長さ100のベクトル
v2 = torch.mv(m, v)
print(v2)

#行列積
m2 = torch.mm(m.t(), m)
print(m2)

#特異値分解
u, s, v = torch.svd(m)
print(u, s, v)

tensor(8.6410)
tensor([ 3.0552, -4.9656, -0.3706, -1.5008,  0.8428, -2.0786, -4.7003,  5.5642,
        -0.9778, -1.4360,  4.3887,  1.3637,  0.2741,  1.5765,  1.7981,  2.6438,
        -3.1943,  4.5198, -4.0566,  2.6220, -4.9353,  3.6402, -3.9354,  0.7837,
         3.8119,  1.1269, -3.3311, -4.8648,  1.4387, -0.0417,  0.7232,  1.8020,
        -3.9912,  5.3805,  3.4341,  1.5991, -3.2554, -4.3200, -0.9929,  1.6353,
         1.1453,  0.6694, -0.8084,  7.3039, -3.7780, -1.6580, -1.3268,  2.1022,
        -0.2467,  2.0536,  0.4151, -3.0901,  1.6455, -3.5065,  3.6270, -1.6390,
         4.6965,  2.1679,  0.3396, -4.1576,  1.0925,  0.5582,  0.4354,  5.6100,
        -8.6603,  1.1885,  0.9675,  2.9441, -2.3547,  0.6494, -5.2287, -1.2603,
         2.8948,  0.3072,  0.9793,  1.3855, -2.2348,  5.0926,  1.6086,  3.7338,
        -5.7040,  5.4172, -4.8571,  1.4611, -1.6192,  5.5331,  0.0207,  4.4199,
         2.7856,  0.0100,  2.3203,  3.1506, -0.1568,  1.4344,  6.4051,  2.1338,
         1.6958,  0.8074,

In [37]:
x = torch.randn(100, 3)
#微分の変数として扱う場合はrequires_gradフラグをTrueにする
a = torch.tensor([1, 2, 3.], requires_grad=True)
print(x)
print(a)

#計算をすることで，自動的に計算グラフが構築されていく
y = torch.mv(x, a)
o = y.sum()
print(y)
print(o)

#微分を実行する
o.backward()


tensor([[ 1.9072e+00, -1.4506e+00,  1.5428e+00],
        [-5.3673e-02,  1.1604e+00, -7.9328e-01],
        [-2.4731e-03,  1.0639e+00, -5.8548e-01],
        [-6.6039e-01, -1.2179e+00,  6.5765e-01],
        [-3.2498e+00, -6.8792e-02, -5.4772e-01],
        [-2.6508e-01,  1.5242e-01, -1.1160e-01],
        [-3.7841e-01, -1.4724e-01, -6.5126e-01],
        [ 1.0265e-01,  5.9380e-01,  8.7785e-01],
        [ 7.1808e-02,  1.2129e+00,  1.1729e+00],
        [-9.2151e-01,  1.0108e+00, -1.1020e-01],
        [-6.6725e-01,  4.9443e-01, -2.9207e-01],
        [ 5.9220e-01, -5.5286e-01,  1.4492e-01],
        [ 1.7762e+00, -1.7109e+00,  8.2596e-01],
        [ 5.1045e-01, -1.5940e+00, -1.1234e+00],
        [-6.0577e-01, -1.3097e+00,  1.6862e+00],
        [ 1.9860e-01, -4.1692e-01,  9.5211e-01],
        [ 5.6402e-01,  5.8568e-01, -5.6132e-02],
        [ 1.0817e+00,  7.8411e-01, -1.8793e-01],
        [-1.3457e+00,  1.3970e+00,  2.4513e-01],
        [ 5.5926e-01, -7.0245e-02, -5.8212e-02],
        [-1.2273e+00